name: sluice
summary: rate limiting data piping tool
description: Sluice reads from standard input and write to standard output at a specified data rate.  This can be useful for benchmarking and exercising I/O streaming at desired throughput rates.
confinement: strict
assumes: [snapd2.45]
base: core20
adopt-info: sluice
grade: stable
adopt-info: sluice

architectures:
    - build-on: s390x
    - build-on: ppc64el
    - build-on: arm64
    - build-on: armhf
    - build-on: amd64
    - build-on: i386

parts:
    sluice:
        plugin: make
        source: git://kernel.ubuntu.com/cking/sluice
        override-pull: |
            snapcraftctl pull
            description="$(git describe HEAD --tags)"
            sha=$(echo $description | tr '-' ' ' | awk '{print $NF}')
            version=${description%$sha}
            commits=$(git log --oneline | wc -l)
            date=$(date +'%Y%m%d')
            if test "$description" = "$sha"
            then
                version="$description"
            else
                version=$(echo $version$date-$commits-$sha | cut -c1-32)
            fi
            snapcraftctl set-version "$version"

        build-packages:
            - gcc
            - make

apps:
    sluice:
        command: usr/bin/sluice

